NAME=Animal
SRC =  main.cpp cat.cpp Dog.cpp Animal.cpp WrongAnimal.cpp WrongCat.cpp Brain.cpp 
OBJ=$(SRC:.cpp=.o)
CXX=c++
CXXFLAGS = -Wall -Wextra -Werror  -std=c++98

all:$(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)
clean:
	@rm -f $(OBJ)
fclean: clean
	@rm  -f $(NAME)
re: fclean all